sudo: false
os:
  - windows
  - linux
  - osx
language: node_js
node_js:
  - "10.16"
  - "12.7.0"
install:
  - npm ci
  - npm run packages-install
  - npm run packages-build
  - cd integration/app-with-serverless-offline && npm ci && cd ../../
script:
  - npm run lint
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then npm test; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run coveralls; fi
  - npm run integration
